version: 2.1

jobs:
  build-test:  # If more build steps are required, add the here
    docker:
      - image: circleci/node:10.19.0
    steps:
      - checkout
      - run:
          name: Get yarn for packet management
          command: sudo apt install yarn -y
      - run:
          name: Test yarn
          command: yarn -v
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Validate dependencies
          command: yarn list

workflows:
  static-testing:
    jobs:
      - build-test